[package]
name = "open-cds-parser"
version = "0.0.1"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.8"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
regex = "1"
ast-term-derive = { path = "./macros/ast-term-derive" }